spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account-enquiry-db
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/base

springdoc:
  api-docs:
    path: /account-enquiry-docs